version: "3"

services:
  postgres:
    volumes:
      - ./files/db:/var/lib/postgresql/data
  megamon:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "1234:1234"
    volumes:
      - ./files:/app/files




